apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        supplementalGroups: [4000]
      volumes:
        - name: psql-storage
          persistentVolumeClaim:
            claimName: psql-pvc
      containers:
        - name: postgres
          image: postgres:17.5
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: psql-storage
          envFrom:
          - secretRef:
              name: psql-lib-secret
          - configMapRef:
              name: psql-lib-configmap
          # env:
          #   - name: POSTGRES_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: secret
          #         key: psql-lib-user
          #   - name: POSTGRES_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: secret
          #         key: psql-lib-password


---

apiVersion: v1
kind: Service
metadata:
  name: psql-lib-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432